MSG_NO_PERMISSION = "Nie masz uprawnień do wywołania tej funkcji."
MSG_WRONG_CHANNEL = "Komendy można używać tylko podczas rekrutacji."
SUMMARY_TITLE = "Podsumowanie rekrutacji"
SUMMARY_OFFICER_ROLE_NAME = "Oficer"
SUMMARY_RECRUITMENT_TYPE = "Typ podania"
SUMMARY_USER = "Użytkownik"
SUMMARY_DELIMITER = "=============================="
SUMMARY_FILE_NAME = "historia_wiadomosci.txt"
SUMMARY_RESPONSE = "Przenoszę podanie do {channel_name}."
CMD_NAME = "rekrutacja"
CMD_DESCRIPTION = "Zarządzaj podaniem rekrutacyjnym - zaakceptuj, odrzuć lub oznacz jako brak kontaktu."
CMD_CHOICE_ACCEPTED = "Zaakceptowany"
CMD_CHOICE_REJECTED = "Odrzucony"
CMD_CHOICE_NO_CONTACT = "Brak kontaktu"
